<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>KendoNET.DynamicLinq.Test</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nunit" Version="3.14.0"/>
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.11"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.11"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\KendoNET.DynamicLinq.csproj"/>
  </ItemGroup>

</Project>
